project:
  type: website
  output-dir: docs

website:
  title: "Publications Explorer"
  navbar:
    left:
      - text: "Dashboard"
        file: index.qmd
      - text: "Citations"
        file: citations.qmd
      - text: "About"        
        file: about.qmd      
  page-footer:                 
    left: "Questions or corrections? <a href='mailto:spalos@celeration.org'>spalos@celeration.org</a>"

format:
  html:
    css: 
      - custom.css
    theme: cosmo
    primary: "#E91E63"
    toc: false
